file:"C:\\ProgramData/Git/config"	core.symlinks=false
file:"C:\\ProgramData/Git/config"	core.autocrlf=true
file:"C:\\ProgramData/Git/config"	core.fscache=true
file:"C:\\ProgramData/Git/config"	color.diff=auto
file:"C:\\ProgramData/Git/config"	color.status=auto
file:"C:\\ProgramData/Git/config"	color.branch=auto
file:"C:\\ProgramData/Git/config"	color.interactive=true
file:"C:\\ProgramData/Git/config"	help.format=html
file:"C:\\ProgramData/Git/config"	rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslcainfo=C:\Program Files\Git\mingw64\ssl\certs\curl-ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig	http.sslverify=false
file:C:/Program Files/Git/mingw64/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig	credential.helper=manager
file:C:/Users/dimi/.gitconfig	user.email=post.ddemin@gmail.com
file:C:/Users/dimi/.gitconfig	user.name=2d
file:C:/Users/dimi/.gitconfig	http.sslcainfo=C:\Program
file:C:/Users/dimi/.gitconfig	http.sslcainfo=C:\Program
file:C:/Users/dimi/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/dimi/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/dimi/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/dimi/.gitconfig	filter.lfs.required=true
file:C:/Users/dimi/.gitconfig	credential.helper=manager
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/2D/technopark.berlin.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
